name: 'PR Title Check'

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize

jobs:
    main:
        name: PR Title Check
        runs-on: ubuntu-latest
        steps:
            # Please look up the latest version from
            # https://github.com/amannn/action-semantic-pull-request/releases
            - uses: amannn/action-semantic-pull-request@v5.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
