# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Technotic Publish Action

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Define branch name'
                required: true
                default: 'production'
            version-type:
                description: 'Define version type!, [major | minor | patch]'
                required: true
                default: 'minor'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.inputs.branch }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
            - uses: 'phips28/gh-action-bump-version@master'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  version-type: ${{ github.event.inputs.version-type }}
                  target-branch: ${{ github.event.inputs.branch }}

    publish-npm:
        needs: release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.inputs.branch }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    create-pr:
        needs: publish-npm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: devops-infra/action-pull-request@v0.5.5
              id: create_pr
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  source_branch: production
                  target_branch: master
                  title: 'ci: automated production sync to master'
                  body: '**Automated pull request**'
                  reviewer: RnDBNCC
                  assignee: RnDBNCC
                  label: automated-pr
                  template: .github/PULL_REQUEST_TEMPLATE.md
                  old_string: 'Explain the task'
                  get_diff: true
                  ignore_users: 'dependabot'
                  allow_no_diff: false
            - uses: reitermarkus/automerge@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  merge-method: squash
                  pull-request: ${{ steps.create_pr.outputs.pr_number }}
                  dry-run: true
