# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Technotic Publish Action

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Define branch name'
                required: true
                default: 'production'
            version-type:
                description: 'Define version type!, [major | minor | patch]'
                required: true
                default: 'minor'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.inputs.branch }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
            - uses: 'phips28/gh-action-bump-version@master'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  version-type: ${{ github.event.inputs.version-type }}
                  target-branch: ${{ github.event.inputs.branch }}

    publish-npm:
        needs: release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.inputs.branch }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    create-pr:
        needs: publish-npm
        runs-on: ubuntu-latest
        steps:
            - run: |
                  curl -o git-chglog -L https://github.com/git-chglog/git-chglog/releases/download/0.9.1/git-chglog_linux_amd64
                  chmod u+x git-chglog
                  ./git-chglog -o CHANGELOG.md
                  rm git-chglog
            - uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: "feat: auto sync"
                  title: "chore: auto sync after production release"
                  body: Update changelog to reflect release changes and sync after production release
                  branch: production
                  base: master
