name: size-limit
on:
    pull_request:
        types: [opened, synchronize]

jobs:
    size:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: andresz1/size-limit-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  build-script: "npm ci && npm run build"
                  clean-script: "clean-lockfiles"
